
#type: args

train:
  num_epochs: 3000 ### 15
  num_epochs_show: 1
  lrList: [1.e-3]
  n_seq: 40
  train_len: 75
  test_len: 25
  T_end: 2
  USE_BASIC_SOLVER: True

model:
  hidden_dim: 60
  num_layers: 3
  augment_dim: 1
  aug_ini_hiddendim: 1

input:
  tSwitchPoint: [0.1] # [0.1, 0.5, 0.8] # [0.06, 0.1,0.24,0.3,0.43, 0.5,0.6]
  tSwitchLen: 0.8 # 0.1
  xVal: [0, 1]

select_model:
  my: 1
  CDE: 1
  NeuralODE: 1
  AugNeuralODE: 1

select_metrics:
  mse: 1
  absErr: 0
  maxErr: 0


